version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: myapp-server
    container_name: node-server
    command: /usr/src/app/node_modules/.bin/nodemon server.js
    volumes:
      - ${WEBAPP_STORAGE_HOME}/server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    networks:
      - item-network
  mongo:
    image: mongo
    volumes:
      - ${WEBAPP_STORAGE_HOME}/data-volume:/data/db
    ports:
      - '27017:27017'
    networks:
      - item-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: myapp-client
    container_name: react-client
    command: yarn start
    volumes:
      - ${WEBAPP_STORAGE_HOME}/client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - '3000:3000'
    networks:
      - item-network
    tty: true

networks:
  item-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
